### ISSUE TITLE
uuid 2.0.0 compatibility?

### ISSUE THREAD

**Issue by asrendon** [d3xt3r2909/linkedin_login#1]
Hello, bit of an issue on my end.
As of right now, the plugin will not work because I need to have uuid 1.0.3 but I currently have only uuid 2.0.0. I cannot downgrade to uuid 1.0.3 either due to flutter_cache_manager being dependent on uuid 2.0.0

I dont suppose there is any work currently being done to upgrade to uuid 2.0.0 compatibility?

**Comment by d3xt3r2909** [comment]
Give me one day or two I will upgrade it if it is possible. Or at least I can make something that you can provide uuid without library dependency.

**Comment by d3xt3r2909** [comment]
Hi @asrendon, 

I have updated versions of libraries that my library depending on SHA-c3187b2f2d66b7e826a8d5e9012c26c32869a4c5

Please check is, so that we can close this issue. 

Thank you for the opening issue. 

Nihad

**Comment by asrendon** [comment]
Hi Nihad, appreciate the quick responses. I wont be able to test unfortunately as the newer version is not in dartlang site yet, unless there is another way to test?

**Comment by d3xt3r2909** [comment]
Hi, hmm noup. But as far as I know it should be already on pub dart lang: 

https://pub.dartlang.org/packages/linkedin_login#-installing-tab-

It is version 0.1.1?

**Comment by asrendon** [comment]
The problem I see was that I'm using cached_network_image: ^0.7.0 which is reliant on the uuid ^2.00
but then when I use uuid ^2.0.0, i get the error that the linkedin plugin requires an older uuid.

If you made a change to the code, I believe you might have to increase the version number as no new linkedin_login plugin will download because its already at the current version. It was already at version 0.1.1

**Comment by d3xt3r2909** [comment]
Wow, my big mistake. I was pretty sure that I have changed that one. You will have it tomorrow for sure. Sorry for time wasting

**Comment by d3xt3r2909** [comment]
Hi, I have updated everything. It should work now

**Comment by asrendon** [comment]
Nihad, its wonderful. The plugin works extremely well. Better than I thought. I'll try and make time to create a video on this so people know about this wonderful plugin, thank you again.

**Comment by d3xt3r2909** [comment]
@asrendon did you make this, because I was planing to make it? But if you did, I can put it on documentation?
