### ISSUE TITLE
Can't Open Login Page Linkedin

### ISSUE THREAD

**Issue by bayuramadeza** [d3xt3r2909/linkedin_login#10]
Since last week, i can't open login page, Loader just turn around and  I got this warning

![WhatsApp Image 2019-11-04 at 15 27 03](https://user-images.githubusercontent.com/32892647/68107504-a9d2b580-ff17-11e9-8fc4-2d28c7132948.jpeg)

>  [INFO:CONSOLE(1)] "document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.", source: https://static-exp1.licdn.com/sc/h/dkkz73ktfmfj3zhtcfnazawui (1)

After i read the documentation LinkedIn, i found this
<img width="818" alt="Screen Shot 2019-11-04 at 14 48 51" src="https://user-images.githubusercontent.com/32892647/68105851-5f9b0580-ff12-11e9-86c2-c27ffcedc3f9.png">

**Comment by d3xt3r2909** [comment]
Hi, 

I have now run the example project and everything works fine.  Can you please also do the same? (Change clientId, redirectUrl, clientSecret) 

If you can please check: 
-  did you change clientId and clientSecret & redirectectUrl to connect LinkedIn app with your application. [(Flow explanation)](https://docs.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow?context=linkedin/consumer/context)
- did you properly registered your app on LinkedIn ? 

Message that you are getting (document.registerElement) is just console message and warning it should't affect on library. But anyway I will updated this error. Thank you for reporting it. 

If nothing of these helps you please tell me.

**Comment by bayuramadeza** [comment]
Okay, i think the problem is background service from firebase_messaging, If i didn't use .Application it works well.
