### ISSUE TITLE
linkedInUser data returns null

### ISSUE THREAD

**Issue by gonharry** [d3xt3r2909/linkedin_login#15]
Hi, i'm trying to connect my first flutter app to LinkedIn and after I do all the configurations and reading the examples the widget returns token and email with no problem, but Firstname and Lastname label return null.

The user in this test is my own account and I have firstname and lastname in my LinkedIn Profile.

What could it be?

`
onGetUserProfile: (LinkedInUserModel linkedInUser) {
      print('Access token ${linkedInUser.token.accessToken}');
      print('First name: ${linkedInUser.firstName.localized.label}');
      print('Last name: ${linkedInUser.lastName.localized.label}');
      print('Email:${linkedInUser.email.elements.first.handleDeep.emailAddress}');
}`

> 2020-02-25 10:22:55.414 8110-8191/cl.xxx.xxx I/flutter: Access token AQVK-vyULOW1sS95KG3laaz-AkV_YJynF9fRg6Qzs4ijCkMBe40Ct4Csw4oD7aD2gT4Du0AGsKgx5damkUeTO9DjbXKHQb5AnLquSpjpPM9QIlMbJZ_OZZZCvHTgbEpzkLme_aG3akdTr4ibaSYGgALuXFeAvO8acNopyfjls3fYJ0zfySMTRH9FiDr25G_qaLWuhFeMDGc8hjJF4Z-X4mSs82AS-sM0CLGTloPIeQrde1tYVEOY7TNgd3yVleohtN3Ej7tvLxIQCgbBkrfe7BJwKyqKxUM8i8BcK5JgBuNzqsEc5IwnbydYtj6QtUmhEEczgjuX9FFNuG1FdqHQgInranMnGA
2020-02-25 10:22:55.414 8110-8191/cl.xxx.xxx I/flutter: First name: null
2020-02-25 10:22:55.414 8110-8191/cl.xxx.xxx I/flutter: Last name: null
2020-02-25 10:22:55.415 8110-8191/cl.xxx.xxx I/flutter: Email: xxx@gmail.com

**Comment by d3xt3r2909** [comment]
Hi @gonharry, 

I am glad, that you are using my lib, please give me a star on this repo and like  on the [pub](https://pub.dev/packages/linkedin_login). 

Can you please check in your app on LinkedIn do you have these permissions like on the image.
![image](https://user-images.githubusercontent.com/17637299/75255167-c99d2a80-57e1-11ea-958f-a4ae0f433525.png)

If this is not causing an issue, can you please check with my example, just run it, without changing anything.

Please give me feedback on this after you try. 

Thanks

**Comment by gonharry** [comment]
Yes, I have these permissions:

<img width="802" alt="Captura de Pantalla 2020-02-25 a la(s) 11 38 19" src="https://user-images.githubusercontent.com/1956789/75257399-a95e7300-57c3-11ea-8e7e-ae4899ae3f08.png">

Gonna check with your demo, because I just copy paste the widget in the example and change your vars with mine, so maybe something went wrong in the linkedin app configuration.

Thanks in advance. I will be back with my report in while.

**Comment by d3xt3r2909** [comment]
Hey @gonharry, thanks for the quick response. Yes, please check it, because I have tested it right now and it works on my side. Maybe is something with LinkedIn app config

**Comment by gonharry** [comment]
Well, I think is my account now...

With your example app I just put two lines to Log the Firstname and Lastname and with my LinkedIn account returns null again. Gonna check with another account to verify again.

`onGetUserProfile: (LinkedInUserModel linkedInUser) {
                        print('Access token ${linkedInUser.token.accessToken}');
                        print('Firstname ${linkedInUser.firstName.localized.label}');
                        print('LastName ${linkedInUser.lastName.localized.label}');
                        print('User id: ${linkedInUser.userId}');
                        user = UserObject(
                          firstName: linkedInUser.firstName.localized.label,
                          lastName: linkedInUser.lastName.localized.label,
                          email: linkedInUser
                              .email.elements[0].handleDeep.emailAddress,
                        );
                        setState(() {
                          logoutUser = false;
                        });
                        Navigator.pop(context);
                      }`

> 2020-02-25 11:52:07.337 21211-21364/com.example.example I/flutter: Access token AQWOu6-P7k1K8Z6eV5U9OFtp9M2LGd2WXgiSSWOf-0qwpHCqO5q6sBCns36W6DB_Ze8FKU0dLvJOlaID9Pe5Zmi9pxMAwL1sHvWNSxM9p8-GAFj5uC8asDO0Dadc51enkvJRb1mePY6_V00-UlAB8u12FTSAQjjgnvcpaAC1UmSbD31r_eckqg3p_3WZgSl7khnjDnFNS9WdnRLqu5slDbBN3q6DMG_RSrWZtq6i7THLyLFN9i-gB_h-6ModK_9P6Um5x1Uy-ktd-q1BWJEUtG3bfW2Qn1eqOZ4yH1dNMixnWeO0yEz956xTTugoAZ0Qa0H629GwSd6vA0ryPpwAHaJ-PZjQWg
2020-02-25 11:52:07.337 21211-21364/com.example.example I/flutter: Firstname null
2020-02-25 11:52:07.337 21211-21364/com.example.example I/flutter: LastName null
2020-02-25 11:52:07.337 21211-21364/com.example.example I/flutter: User id: NTt0aO1EK0

**Comment by gonharry** [comment]
Yes, it's my account but now idk how to fix it. Another friend tested your demo and he is getting everything fine.

If it's my account I think i will close and comment and try to figure it out.

Thanks for the help!

> 2020-02-25 12:13:11.346 21211-21364/com.example.example I/flutter: Access token AQXL2pm_kL4WlbNQJbMCEa6pLD5VLmplJeoVCT-kn32dYwv54GGTufWRDfbaqoov8YOqigdz1TdXdZfZ8MGqIsNaTATgQj_XI_ISnBdnrg5lS4iSPWrfnPvbU5NHkV9W-pjRocAtow3wBOwAKVMaxU2nAgfiIV3xgUHu6Lq7LCApvbriYRbrTp-r2U7xlcWOjlF16NzSRlBpq_3xI8HODWt_Ih91cW6JOqYanunk-kZr9ng90aP7d4wKATKcg4k3habVQdnDi53GTQRxlXhpaTrqCtBpjrz6e98X39XxuxCRf8Rz9Bh_oCqhc6NMw9KYRTxUW4hdaj0wNyf2x-S090ZmdTHtXg
2020-02-25 12:13:11.346 21211-21364/com.example.example I/flutter: Firstname Jorge
2020-02-25 12:13:11.346 21211-21364/com.example.example I/flutter: LastName Aguilera
2020-02-25 12:13:11.346 21211-21364/com.example.example I/flutter: User id: wJ6zF28VLN

**Comment by d3xt3r2909** [comment]
If I can help you somehow, please let me know

**Comment by alican** [comment]
Hey @gonharry 
I have the same issue. E-Mail and User id is fine but first name and last name ist just returning null.
Maybe it has do something because of the local settings on linkedin.

**Comment by gonharry** [comment]
@alican After I updated my account with the same Name and Lastname on LinkedIn, LinkedIn API returns the data ok. I think that maybe it's a LinkedIn issue when your account is not updated since some years. Make those changes and wait an hour or two, then test the plugin and see the changes.

**Comment by d3xt3r2909** [comment]
Thanks for explaining this. Will include into the documentation, @gonharry .
