### ISSUE TITLE
Setting the height of the AppBar (WebView)

### ISSUE THREAD

**Issue by ricardonior29** [d3xt3r2909/linkedin_login#23]
WebviewScaffold allows to use PrefferedSize instead of AppBar to change the height

**Comment by d3xt3r2909** [comment]
@ricardonior29 Thanks for the contribution. 

Please add more details, why should we change to `PrefferedSizeWidget`, and not use `AppBar`. Because I am planning to add a reference to his issue in changelog file.

Thanks

**Comment by d3xt3r2909** [comment]
@ricardonior29  any feedback on this?

**Comment by d3xt3r2909** [comment]
Please open it again if there is a need
