### ISSUE TITLE
how can we get profile image?

### ISSUE THREAD

**Issue by vbakale** [d3xt3r2909/linkedin_login#29]
I am try trying to implement getting profile image with this package it seems to be crashing while fetching image or i may have done something wrong. Can you please update how can we access profile image with this package?

**Comment by d3xt3r2909** [comment]
Hi, 

The library is only for sign in with Linkedin and nothing else. (But maybe I will consider adding a method for fetching image info also. 

For now what you can do is: 

1. Make request to https://api.linkedin.com/v2/me?projection=(id,profilePicture(displayImage~:playableStreams))&oauth2_access_token=HERE 
2. Change `HERE` with an access token that you will fetch with this library 

![image](https://user-images.githubusercontent.com/17637299/87644494-802b8880-c74c-11ea-9161-d3a230bf6b04.png)

**Comment by d3xt3r2909** [comment]
Did this helped to you, Mr @vbakale ?

**Comment by vbakale** [comment]
i just want to display profile picture with first and last name after logged in with likedin.

user = UserObject(
                                firstName: linkedInUser.firstName.localized.label,
                                lastName: linkedInUser.lastName.localized.label,
                                email: linkedInUser
                                    .email.elements[0].handleDeep.emailAddress,
                                  **profilePicture: '${linkedInUser.profilePicture.displayImage}'**
                              );


CircleAvatar(
                          radius: 40,
                          **backgroundImage: NetworkImage('${user?.profilePicture}'),**
                        ),

Now in networkImage i require URL to work its showing blank.

> Did this helped to you, Mr @vbakale ?

**Comment by d3xt3r2909** [comment]
It's showing blank because, in the object of profilePicture, LinkedIn is not returning URI address of the image. To be able to get URI of the user image you need to use Access Token + 
https://api.linkedin.com/v2/me?projection=(id,profilePicture(displayImage~:playableStreams))&oauth2_access_token=HERE

The response of this GET method will return you a URI, which you can use on the placeholder.

**Comment by vbakale** [comment]
> It's showing blank because, in the object of profilePicture, LinkedIn is not returning URI address of the image. To be able to get URI of the user image you need to use Access Token +
> https://api.linkedin.com/v2/me?projection=(id,profilePicture(displayImage~:playableStreams))&oauth2_access_token=HERE
> 
> The response of this GET method will return you a URI, which you can use on the placeholder.



> It's showing blank because, in the object of profilePicture, LinkedIn is not returning URI address of the image. To be able to get URI of the user image you need to use Access Token +
> https://api.linkedin.com/v2/me?projection=(id,profilePicture(displayImage~:playableStreams))&oauth2_access_token=HERE
> 
> The response of this GET method will return you a URI, which you can use on the placeholder.



> It's showing blank because, in the object of profilePicture, LinkedIn is not returning URI address of the image. To be able to get URI of the user image you need to use Access Token +
> https://api.linkedin.com/v2/me?projection=(id,profilePicture(displayImage~:playableStreams))&oauth2_access_token=HERE
> 
> The response of this GET method will return you a URI, which you can use on the placeholder.

Okay ill check that. Thank you for help:)

**Comment by d3xt3r2909** [comment]
I will try also to make helper function for this or to add to as an option. Will notify you. Thanks for opening an issue.

**Comment by d3xt3r2909** [comment]
@vbakale  if you can wait I will publish new release in couple of hours with this, otherwise you can use the approach 🆙

**Comment by d3xt3r2909** [comment]
Hi @vbakale,

it's implemented. Please see the README file and check the example project on how to use the `projection` property. 

For your case you should provide to `LinkedInUserWidget` under `projection` parameter, those values: 

```
projection:  [
    ProjectionParameters.id,
    ProjectionParameters.localizedFirstName,
    ProjectionParameters.localizedLastName,
    ProjectionParameters.firstName,
    ProjectionParameters.lastName,
    ProjectionParameters.profilePicture,
 ]
```

As a result, inside `onGetUserProfile` callback, you can use something like this: 

```
    linkedInUser?.profilePicture?.displayImageContent?.elements[0]?.identifiers[0]?.identifier
```

All of this is based on this response from LinkedIn (in case you wanna check the structure of image object): 

https://api.linkedin.com/v2/me?projection=(id,localizedLastName,firstName,lastName,localizedFirstName,profilePicture(displayImage~:playableStreams))&oauth2_access_token=YOUR_ACCESS_TOKEN

YOUR_ACCESS_TOKEN - you can get it from `linkedInUser.token` inside `onGetUserProfile` callback. 


I will close the issue for now, but please be free if something is missing/not working. 

And if you didn't already please ⭐ the repo and give me a like on [pub.dev package](https://pub.dev/packages/linkedin_login).

Many thanks.
