### ISSUE TITLE
token not retrieved

### ISSUE THREAD

**Issue by santaanto** [d3xt3r2909/linkedin_login#37]
I have tried the example app.
I have set up Linkedin page for my app with the permissions for : 

r_emailaddress 
r_liteprofile

My redirect url is youtube.com, just for test.
I copied the ClientID and Client Secret and redirect url ( https://youtube.com) and used them on the example app. I haven't changed any other lines of the example app code.
I launch the app on my phone from the Android Studio debugger, I can see the three buttons on the screen, I choose the "get token" one , It goes to the Linkedin log-in page, on the bottom it is written you will be redirected to youtube.com.
When I insert correct username and password , the app takes me to youtube.com but nothing about the authorization token is printed to the console. 
Also how can I then get the profile info and email address ? The app is now showing youtube.com and if I go back it takes me again to the Linkedin log in.
I have not noticed authorization errors on the console log.
Am I missing something ?

thank you

**Comment by d3xt3r2909** [comment]
Hi @santaanto, 

The thing is that `https//youtube.com` has some scripts on the initial loading of the page, which are redirecting you to something totally unexpected (google ads, modals for privacy, CMP, etc). 

1. Please check did you add correctly `redirect_url` to your settings of the app on `https://www.linkedin.com/developers/apps/{YOUR_APP_ID}/auth`

Should be something like this: 

![image](https://user-images.githubusercontent.com/17637299/100429823-3063b300-3096-11eb-9414-c4a24a7f8a3a.png)

2. And please try to use as on the picture, URL similar to this (it cannot have some javascript stuff): 

`https://www.youtube.com/callback`

I'm making a new version (v2) of this library and will try to somehow see is it possible to notify devs about this issue.

Please give me a ⭐ star on the repo ⭐ , and 👍🏿 like on [pub.dev](https://pub.dev/packages/linkedin_login) 👍🏿 if you didn't already.

**Comment by santaanto** [comment]
ah that's why. 
I have now used a pure text webpage as redirect url.
I can now get the access token correctly and I see it on the "auth code" page of the app.
If instead I try logging in from the "Profile" page on the app, I get the page loading forever, it never returns.

**Comment by d3xt3r2909** [comment]
Can you give me a redirect URl which you are using now, because I cannot reproduce that?

- did you update URL in settings of app on LinkedIn page? 
-it is happening with example app? If yes, can you reinstall application maybe it's cached from last time

**Comment by d3xt3r2909** [comment]
Same issue as here #25

**Comment by d3xt3r2909** [comment]
Any feedback from you @santaanto so that I can close a ticket

**Comment by santaanto** [comment]
Thank you for your reply.
I am using this redirect page chosen randomly as it was text only :
https://www.york.ac.uk/teaching/cws/wws/webpage1.html

This is the log I get on Android Studio when I try on "profile" form on the app to sign in:

I/ViewRootImpl@afb9f1c[MainActivity]( 5384): ViewPostIme pointer 0
I/ViewRootImpl@afb9f1c[MainActivity]( 5384): ViewPostIme pointer 1
I/WebViewFactory( 5384): Loading com.google.android.webview version 86.0.4240.198 (code 424019833)
I/cr_LibraryLoader( 5384): Loaded native library version number "86.0.4240.198"
I/cr_CachingUmaRecorder( 5384): Flushed 5 samples from 5 histograms.
W/chromium( 5384): [WARNING:dns_config_service_posix.cc(342)] Failed to read DnsConfig.
W/example.exampl( 5384): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
W/cr_media( 5384): Requires BLUETOOTH permission
I/mali_egl( 5384): eglDestroySurface() in
I/mali_egl( 5384): eglDestroySurface() out
D/libmdf  ( 5384): libmdf v2.9.0.0 On 64bit PLATFORM
I/flutter ( 5384): Access token AQUO3gpJiaJvnaH3wWkZc4mPupXf55koa-5DE1WiNKEWtmdHrGYiyY3ft8U97uRUngsPaMZrHjlG2Vgza7UsFKH1fkl7hXLVJ-D3PmHlVJOsFGV6UOZduZvr3tuMbCpUuvcJRwyrb0kzKbtNGqTIPWRhy3BbxCFAz-xXr6NTJpi8LrdXKVRmVSkrj4oVJX5-sgLnarJOiTiyAx7-Pjva3HIO9CwRW2ihD_ClsJNhmOnx-ie8dFGDyYPCMWCno0zkXmVdQ0UwS6FwVHwb8n_PC2LDBIAT6ZM5a3hEBvlmFdyR0vJ2EjO3oJRbT63OLRKUwg5nKVPtlu_WPWHyhi9LoqqBfXTxRA
I/flutter ( 5384): User id: SMsG-DYrw6
E/flutter ( 5384): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter ( 5384): Receiver: null
E/flutter ( 5384): Tried calling: [](0)
E/flutter ( 5384): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 5384): #1      _LinkedInProfileExamplePageState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:example/main.dart:99:103)
E/flutter ( 5384): #2      _LinkedInUserWidgetState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:linkedin_login/src/client/linked_in_user_widget.dart:101:42)
E/flutter ( 5384): #3      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 5384): #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 5384): #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 5384): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 5384): #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 5384): #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 5384): #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter ( 5384): #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter ( 5384): #11     _withClient (package:http/http.dart)
E/flutter ( 5384): <asynchronous suspension>
E/flutter ( 5384): #12     get (package:http/http.dart:46:5)
E/flutter ( 5384): #13     _LinkedInUserWidgetState.build.<anonymous closure>.<anonymous closure> (package:linkedin_login/src/client/linked_in_user_widget.dart:82:17)
E/flutter ( 5384): #14     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 5384): #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 5384): #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 5384): #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 5384): #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 5384): #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 5384): #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter ( 5384): #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter ( 5384): #22     _withClient (package:http/http.dart)
E/flutter ( 5384): <asynchronous suspension>
E/flutter ( 5384): #23     get (package:http/http.dart:46:5)
E/flutter ( 5384): #24     _LinkedInUserWidgetState.build.<anonymous closure> (package:linkedin_login/src/client/linked_in_user_widget.dart:74:15)
E/flutter ( 5384): #25     _LinkedInWebViewHandlerState.initState.<anonymous closure>.<anonymous closure> (package:linkedin_login/src/webview/linked_in_web_view_handler.dart:49:42)
E/flutter ( 5384): #26     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 5384): #27     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 5384): #28     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 5384): #29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 5384): #30     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 5384): #31     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 5384): #32     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter ( 5384): #33     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter ( 5384): #34     AuthorizationWebViewConfig.fetchAuthorizationCodeResponse (package:linkedin_login/src/webview/web_view_widget_parameters.dart)
E/flutter ( 5384): <asynchronous suspension>
E/flutter ( 5384): #35     ViewModel._fetchAuthorizationCodeResponse (package:linkedin_login/src/webview/linked_in_web_view_handler.dart:96:21)
E/flutter ( 5384): #36     _LinkedInWebViewHandlerState.initState.<anonymous closure> (package:linkedin_login/src/webview/linked_in_web_view_handler.dart:48:19)
E/flutter ( 5384): #37     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 5384): #38     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 5384): #39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 5384): #40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter ( 5384): #41     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter ( 5384): #42     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter ( 5384): #43     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter ( 5384): #44     _rootRun (dart:async/zone.dart:1182:47)
E/flutter ( 5384): #45     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 5384): #46     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 5384): #47     _CustomZone.bindCallbackGuarded.<
D/InputMethodManager( 5384): prepareNavigationBarInfo() DecorView@e3f33f0[MainActivity]
D/InputMethodManager( 5384): getNavigationBarColor() -855310
V/InputMethodManager( 5384): Starting input: tba=com.example.example ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 5384): startInputInner - Id : 0
I/InputMethodManager( 5384): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 5384): Input channel destroyed: 'ClientS', fd=106
I/ViewRootImpl@afb9f1c[MainActivity]( 5384): stopped(true) old=false
D/OpenGLRenderer( 5384): makeCurrent EglSurface : 0x7ef1a26600 -> 0x0
I/SurfaceView( 5384): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{a7f30fa V.E...... ........ 0,0-1080,2136} of ViewRootImpl@afb9f1c[MainActivity]
I/SurfaceView( 5384): surfaceDestroyed callback.size 1 #1 io.flutter.embedding.android.FlutterSurfaceView{a7f30fa V.E...... ........ 0,0-1080,2136}
I/mali_egl( 5384): eglDestroySurface() in
I/mali_winsys( 5384): delete_surface() [1080x2136] return
I/mali_egl( 5384): eglDestroySurface() out
W/libEGL  ( 5384): EGLNativeWindowType 0x7e6d5f9010 disconnect failed
I/SurfaceView( 5384): remove() io.flutter.embedding.android.FlutterSurfaceView{a7f30fa V.E...... ........ 0,0-1080,2136} Surface(name=SurfaceView - com.example.example/com.example.example.MainActivity@a7f30fa@0)/@0x309cdc0
I/SurfaceView( 5384): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{a7f30fa V.E...... ........ 0,0-1080,2136} of ViewRootImpl@afb9f1c[MainActivity]
D/OpenGLRenderer( 5384): destroyEglSurface : 0x7ef1a26600
I/mali_egl( 5384): eglDestroySurface() in
I/mali_winsys( 5384): delete_surface() [1080x2280] return
I/mali_egl( 5384): eglDestroySurface() out
E/OpenGLRenderer( 5384): ReliableSurface: perform returned an error
W/libEGL  ( 5384): EGLNativeWindowType 0x7ef19e8f90 disconnect failed
D/OpenGLRenderer( 5384): ~ReliableSurface : 0x7ef19e8f80
I/ViewRootImpl@afb9f1c[MainActivity]( 5384): Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)8 dur=8 res=0x5 s={false 0} ch=false
I/ViewRootImpl@afb9f1c[MainActivity]( 5384): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager( 5384): prepareNavigationBarInfo() DecorView@e3f33f0[MainActivity]
D/InputMethodManager( 5384): getNavigationBarColor() -855310

**Comment by d3xt3r2909** [comment]
Hi @santaanto, 

now the issue is not inside the URL.  As you can see it's throwing you the exception `NoSuchMethodError: The method '[]' was called on null.`  This can be an error somewhere inside `example/lib/main.dart` callback `onGetUserProfile`, most probably you have something disabled on your LinkedIn profile. You should handle those values inside your applications, check for nulls, and show errors. Please, debug which of these lines is giving you that error message.

```
user = UserObject(
       firstName: linkedInUser?.firstName?.localized?.label,
       lastName: linkedInUser?.lastName?.localized?.label,
       email: linkedInUser?.email?.elements[0]?.handleDeep?.emailAddress,
       profileImageUrl: linkedInUser?.profilePicture?.displayImageContent?.elements[0]?.identifiers[0]?.identifier,
 );
```

![image](https://user-images.githubusercontent.com/17637299/100963740-5ae6bd80-3527-11eb-81a1-158e7598b9ce.png)
