### ISSUE TITLE
I'm getting this error

### ISSUE THREAD

**Issue by Raviteja11122** [d3xt3r2909/linkedin_login#4]
E/flutter (23112): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (23112): Receiver: null
E/flutter (23112): Tried calling: []("displayImage")
E/flutter (23112): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter (23112): #1      new _LinkedInProfilePicture.fromJson (package:linkedin_login/src/linked_in_user_model.dart:95:27)
E/flutter (23112): #2      new LinkedInUserModel.fromJson (package:linkedin_login/src/linked_in_user_model.dart:22:37)
E/flutter (23112): #3      _LinkedInUserWidgetState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:linkedin_login/src/linked_in_profile.dart:60:39)
E/flutter (23112): #4      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (23112): #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (23112): #6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (23112): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (23112): #8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (23112): #9      Future._complete (dart:async/future_impl.dart:473:7)
E/flutter (23112): #10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (23112): #11     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
E/flutter (23112): #12     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
E/flutter (23112): #13     _withClient (package:http/http.dart)
E/flutter (23112): <asynchronous suspension>
E/flutter (23112): #14     get (package:http/http.dart:46:5)
E/flutter (23112): #15     _LinkedInUserWidgetState.build.<anonymous closure>.<anonymous closure> (package:linkedin_login/src/linked_in_profile.dart:50:15)
E/flutter (23112): #16     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (23112): #17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (23112): #18     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (23112): #19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (23112): #20     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (23112): #21     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter (23112): #22     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (23112): #23     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
E/flutter (23112): #24     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
E/flutter (23112): #25     _withClient (package:http/http.dart)
E/flutter (23112): <asynchronous suspension>
E/flutter (23112): #26     get (package:http/http.dart:46:5)
E/flutter (23112): #27     _LinkedInUserWidgetState.build.<anonymous closure> (package:linkedin_login/src/linked_in_profile.dart:42:13)
E/flutter (23112): #28     _LinkedInAuthorizationState.initState.<anonymous closure>.<anonymous closure> (package:linkedin_login/src/linked_in_authorization_webview.dart:69:20)
E/flutter (23112): #29     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (23112): #30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (23112): #31     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (23112): #32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (23112): #33     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (23112): #34     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter (23112): #35     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (23112): #36     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
E/flutter (23112): #37     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
E/flutter (23112): #38     _LinkedInAuthorizationState._getAuthorizationCode (package:linkedin_login/src/linked_in_authorization_webview.dart)
E/flutter (23112): #39     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
E/flutter (23112): #40     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (23112): #41     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (23112): #42     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (23112): #43     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (23112): #44     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (23112): #45     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter (23112): #46     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (23112): #47     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
E/flutter (23112): #48     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
E/flutter (23112): #4

**Comment by d3xt3r2909** [comment]
I can look up what is problem tomorrow. Currently I am to far of computer. Can you just describe where did you get this problem?

**Comment by d3xt3r2909** [comment]
Hello again, I think that I have fix bug on this issue. Basically, there was a bug when user does not have profile picture you will get this message.

Please test this again with new version of package. I will close for now this issue, but if you find again same problem we will open again issue. Also, I would appreciate if you can describe problems in more detail information in future. 

Thank you a lot.

**Comment by Raviteja11122** [comment]
thanks buddy
