### ISSUE TITLE
Return authorization code and state

### ISSUE THREAD

**Issue by tuantvu** [d3xt3r2909/linkedin_login#5]
Hi, I would like to keep my client secret behind a backend service. To do so, I would need the authorization code and state, and for the widget to not retrieve the access token. Could you provide a widget that returns back the authorization code and doesn't require the client secret? Great work btw!

**Comment by d3xt3r2909** [comment]
Hello, 

Thanks.

I need also this feature in my project. But I am not sure when I will start work on it. Are you in hurry?

**Comment by d3xt3r2909** [comment]
@tuantvu First of all sorry for a waiting period of time.

I have published a new version of the library with a new widget. From now on, we can use a widget that is called LinkedInAuthCodeWidget to fetch just the authorization code. 

For more details see example in the project.

Thank you for the opening issue. 

Best,
Nihad
