### ISSUE TITLE
Linkedin Login + Firebase auth

### ISSUE THREAD

**Issue by kekko7072** [d3xt3r2909/linkedin_login#52]
Is there a way to easily integrate this package with firebase auth? I'd like to access using this package, then generate a token for accessing in firebase as normal access (ex. email/password or google_sign_in). Is  it possible ?

**Comment by d3xt3r2909** [comment]
Hi @kekko7072  and sorry for the late response. 

There was already a similar question to this one, but I cannot remember where to link you to it. I didn't investigate this possibility but anyhow Firebase is supporting only a few providers out of the box, and for linked in they are expecting to use custom tokens https://stackoverflow.com/a/40041273/6074443. 

I'm closing this as it's not an issue, and it's more question for StackOverflow. 

Of course, if you find a solution please share your knowledge with future readers.

All the best

**Comment by kekko7072** [comment]
Hey I tried and tested some code but nothing worked. Now I am trying to access using this package and `firebase_auth`, this is the my idea:

1) Use this package to sign in and obtain the linkedin token and profile info.
2)Create a firebase credential using the token (not sure about this)
```
OAuthCredential(providerId: kLinkedInClientId, signInMethod: 'password', accessToken: linkedInUser.token.accessToken)

```
3)Sign in with credential ` FirebaseAuth.instance.signInWithCredential(credential);`

Do you think It could work? Any suggestion feel free to report.

**Comment by kekko7072** [comment]
I think this could be a key feature to make this plugin perfect.
