### ISSUE TITLE
Update http dependency 

### ISSUE THREAD

**Issue by devsig** [d3xt3r2909/linkedin_login#55]
Because linkedin_login >=1.0.0 <2.0.0-dev.4 depends on http ^0.12.0+4 and connect depends on http ^0.13.3, linkedin_login >=1.0.0 <2.0.0-dev.4 is forbidden.
So, because connect depends on linkedin_login ^1.3.1, version solving failed.
pub get failed (1; So, because connect depends on linkedin_login ^1.3.1, version solving failed.)

**Comment by d3xt3r2909** [comment]
Please try using `2.0.0-dev.4` version of this library. It should resolved the issue. Let me know if doesn't.

**Comment by d3xt3r2909** [comment]
Please use the new version `2.0.1`. I will close this, as the dependencies versions has been upgraded. Thanks for reporting
