### ISSUE TITLE
[BUG] Keyboard not working

### ISSUE THREAD

**Issue by shreya-prajapati** [d3xt3r2909/linkedin_login#64]
I have flutter applications using Login with LinkedIn where the webview stopped working. Looks like webview_flutter fails to show the (soft) keyboard on Android 12 (API 31), no matter of what kind of input field is clicked. The error can be easily reproduced with the Android emulator when switching between Android 11 and 12.

**Comment by d3xt3r2909** [comment]
Hello, I'm currently on vacation so will not be able to fix that before next week. There are some breaking changes in many plugins regarding A12. I would start with upgrading webview if someone wants to take PR before me.

**Comment by d3xt3r2909** [comment]
Thanks for opening bug

**Comment by d3xt3r2909** [comment]
Hello, I'm back and will start looking at this as soon as possible. Thanks once again for creating & waiting.

**Comment by d3xt3r2909** [comment]
Hey, a "little" update from my side. This issue should be resolved in new version of the app by https://github.com/d3xt3r2909/linkedin_login/pull/66  PR. Please check it and close an issue if it is fixed.

**Comment by shreya-prajapati** [comment]
@d3xt3r2909 Thanks for looking into it asap. 

I have tested with Pixel 4a (android 12), its working fine.

**Comment by d3xt3r2909** [comment]
> @d3xt3r2909 Thanks for looking into it asap.
> 
> I have tested with Pixel 4a (android 12), its working fine.

Super that I helped! All the best, please star the repo and give a like on pub.dev if you didn't. It means a lot. 

Thanks once again for opening the bug and have a nice week.
