### ISSUE TITLE
Opening the Installed LinkedIn app instead of WebView

### ISSUE THREAD

**Issue by gbbest15** [d3xt3r2909/linkedin_login#68]
i am trying to use the plugin in my project, but i was surprise after i click on the sign in  with Linkedin, it keep showing in webview instead of opening the installed Linkedin app to confirm the authentication.

**Comment by d3xt3r2909** [comment]
Hi, did you try with example project? Is it happening the same for you?

**Comment by gbbest15** [comment]
@d3xt3r2909 yes i try the example project. 

what i was expecting is that

immediately you click on the sign in with Linkedin and you have Linkedin app Installed on your phone, the webview is not suppose to show instead it should open up the Linkedin app, just like Login in with facebook and the rest..

**Comment by d3xt3r2909** [comment]
Ah ok, I see @gbbest15, 

Unfortunately, that will not work as you imagined as LinkedIn is not implemented like Facebook. In fact, even google is not implemented like Facebook. Basically depends from provider to provider.  This is how LinkedIn imagined their authentication flow https://docs.microsoft.com/en-us/linkedin/shared/authentication/authentication 

I'm closing this as this is something that's not possible to implement. 

Thanks for opening an issue in anycase, and feel free to reopen if you don't agree.

**Comment by BraianPita** [comment]
Is there any updates from this? Or is it still possible as of 2023 to fetch the current session from the app? Since it completely defeats the purpose of SSO if I cannot do so

**Comment by d3xt3r2909** [comment]
It's still behaviour that linked in API is expecting for external apps
