### ISSUE TITLE
Login invalid_redirect_uri error 400

### ISSUE THREAD

**Issue by EpsilonOrionis** [d3xt3r2909/linkedin_login#75]
Hi, awesome pub, but I get this error when i try to Sign in the profile:

LinkedInLogin: Unable to fetch access token code HttpResponseException: Code 400 for https://www.linkedin.com/oauth/v2/accessToken with {"error":"invalid_redirect_uri","error_description":"Unable to retrieve access token: appid/redirect uri/code verifier does not match authorization code. Or authorization code expired. Or external member binding exists"}

**Comment by d3xt3r2909** [comment]
Closing this as there is no response. Please try to filter all issues by FAQ label it could happen that someone already resolved this issue. Example of this project works.
