### ISSUE TITLE
Build is failing with the following error 

### ISSUE THREAD

**Issue by JERINJACOBCHERIAN** [d3xt3r2909/linkedin_login#8]
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.arch.core:core-runtime' has different version for the compile (2.0.0-rc01) and runtime (2.0.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by d3xt3r2909** [comment]
As far as I know, I have already switch this library to AndroidX. Did you upgraded your app on AndroidX? 

I don't currently have time to go deep in this issue, probably from next week I am OK to work on this, if upgrade of your app not fix this issue.

**Comment by JERINJACOBCHERIAN** [comment]
When I migated this app to androidX,more errors pops up,I will post that too

**Comment by JERINJACOBCHERIAN** [comment]
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.slidingpanelayout:slidingpanelayout' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution

**Comment by JERINJACOBCHERIAN** [comment]
There is no error with the ios builds.

**Comment by d3xt3r2909** [comment]
Hello,

I still don't have time because of my work, really sorry for delay. 

If you know and want every pull request is welcome.

**Comment by d3xt3r2909** [comment]
Hello @JERINJACOBCHERIAN  

Did you manage to fix this issue on your self, or this is still happening? 

I have tried to produce this on my example project of this library, but I don't have anything similar.

**Comment by JERINJACOBCHERIAN** [comment]
I wasn't able to fix this. I am still a beginner in the field and is unable to fix it

**Comment by d3xt3r2909** [comment]
Hello @JERINJACOBCHERIAN 

Please if you can start my example project and see is it working with that project. 

Currently, from this perspective this issue doesn't seems to me that it is related with my library. 

Your issue can be connected with this issue https://github.com/flutter/flutter/issues/27254. 

I will close this issue, but if you still think that is related with my library please write in comments.
