### ISSUE TITLE
[UPGRADE] Please upgrade pub to webview_flutter: ^4.0.1

### ISSUE THREAD

**Issue by khainard** [d3xt3r2909/linkedin_login#80]
Please upgrade pub to webview_flutter: ^4.0.1

**Comment by d3xt3r2909** [comment]
Hey sorry I was busy these few months. Will try to do it ASAP. Thanks for opening ticket

**Comment by d3xt3r2909** [comment]
Ok, I took a quick look into it and it will take me some time to resolve this. ETA would be 5-10 days.

**Comment by d3xt3r2909** [comment]
Hi, could you please try [beta](https://pub.dev/packages/linkedin_login/versions/2.2.2-beta.1) version of package which has migration to v4. Its beta since I really didn't have time to fix tests, but just to try to unblock you girls and guys

**Comment by d3xt3r2909** [comment]
@khainard any feedback?

**Comment by khainard** [comment]
> 

Hi. 
Linkedin integration was declined for my project and i didn't tried beta version.
Thanks a lot for support.

**Comment by d3xt3r2909** [comment]
No worries, have a nice luck while fluttering :]

**Comment by d3xt3r2909** [comment]
Will close this issue, if anyone needs it please use beta version and report an issue. Soon there will be stable version of lib
