### ISSUE TITLE
Integrate with new version of dependencies

### ISSUE THREAD

**Issue by ParhaMDeF** [d3xt3r2909/linkedin_login#87]
Hey, please integrate the package with the new version of Flutter and other dependencies like` http: ^1.1.0` and `Webview`. it has conflicts with the other packages in my app.
thanks

**Comment by d3xt3r2909** [comment]
Hey sorry for long time waiting. It should be resolved from `2.3.x`. 

Will close this issue since it should be resolved, but please let me know if you still have an issues.
